[package]
name = "maquina-virtual"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bitreader = "0.3.11"
eframe = "0.33.0"
phf = { version = "0.13.1", features = ["macros"] }
rfd = "0.15.4"
